<a href="https://colab.research.google.com/github/phani06/Data-Preprocessing/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_excel('/content/sample.csv.xlsx')

In [ ]:
x= df.iloc[1:5,:-1].values 
x 

array([['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan]], dtype=object)

In [ ]:
y= df.iloc[0:5,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes'], dtype=object)

In [ ]:
label_encoder_x= LabelEncoder() 
x[:, 0]= label_encoder_x.fit_transform(x[:, 0]) 
x

array([[1, 27.0, 48000.0],
       [0, 30.0, 54000.0],
       [1, 38.0, 61000.0],
       [0, 40.0, nan]], dtype=object)

In [ ]:
onehot = OneHotEncoder(sparse=False)
x = np.concatenate([x[:,:7],onehot.fit_transform(x[:,1].reshape(-1,1))],axis=1)
x

array([[1, 27.0, 48000.0, 1.0, 0.0, 0.0, 0.0],
       [0, 30.0, 54000.0, 0.0, 1.0, 0.0, 0.0],
       [1, 38.0, 61000.0, 0.0, 0.0, 1.0, 0.0],
       [0, 40.0, nan, 0.0, 0.0, 0.0, 1.0]], dtype=object)

In [ ]:
pip install category_encoders

     |████████████████████████████████| 80 kB 8.3 MB/s 


In [ ]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()

encoded_Purchased = encoder.fit_transform(df.Purchased.values.reshape(-1,1))
encoded_Purchased

array([[0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [ ]:
df['Purchased_Encoded'] = encoded_Purchased
df['Purchased_Encoded'] = df['Purchased_Encoded'].astype('int64')
df

Country   Age   Salary Purchased  Purchased_Encoded
0   France  44.0  72000.0        No                  0
1    Spain  27.0  48000.0       Yes                  1
2  Germany  30.0  54000.0        No                  0
3    Spain  38.0  61000.0        No                  0
4  Germany  40.0      NaN       Yes                  1
5   France  35.0  58000.0       Yes                  1
6    Spain   NaN  52000.0        No                  0
7   France  48.0  79000.0       Yes                  1
8  Germany  50.0  83000.0        No                  0
9   France  37.0  67000.0       Yes                  1

In [ ]:
encoder = OrdinalEncoder()
ord_Emotional_State = encoder.fit_transform(df.Country.values.reshape(-1,1))
ord_Emotional_State

array([[0.],
       [2.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.]])

In [ ]:
df[['Country', 'Salary']].sort_values(by='Salary', ascending=False)

Country   Salary
8  Germany  83000.0
7   France  79000.0
0   France  72000.0
9   France  67000.0
3    Spain  61000.0
5   France  58000.0
2  Germany  54000.0
6    Spain  52000.0
1    Spain  48000.0
4  Germany      NaN